"use client";

import QuoteForm from "../components/quote-form";
import { ProjectFooter, ProjectHeader, useProjectUi } from "../projects/project-shell";

const copy={
 fr:{tag:"À PROPOS D’EPSTAR",title:"Nous transformons les espaces en outils de réussite.",lead:"EPSTAR est une entreprise algérienne spécialisée dans la conception, la fabrication et l’installation d’aménagements sur mesure pour les professionnels et les particuliers.",intro:"De la pharmacie au bureau, du commerce à la chambre, nous réunissons l’étude, le design, la fabrication et la pose sous un même toit. Cette maîtrise globale nous permet de créer des espaces cohérents, fonctionnels et durables.",discover:"Découvrir nos projets",stats:[["4","Univers spécialisés"],["100%","Fabrication sur mesure"],["1","Interlocuteur de l’étude à la pose"]],story:"Un projet réussi commence par une bonne compréhension.",storyText:"Nous ne partons pas d’un catalogue figé. Nous observons le lieu, écoutons les usages et développons une réponse adaptée aux dimensions, au budget et à l’image souhaitée.",valuesTag:"NOS ENGAGEMENTS",valuesTitle:"Une même exigence à chaque étape.",values:[["01","Écoute","Comprendre les besoins réels avant de dessiner la solution."],["02","Précision","Maîtriser les mesures, les matières et chaque détail de finition."],["03","Cohérence","Créer une continuité entre l’esthétique, l’usage et l’identité."],["04","Suivi","Rester présent depuis la première étude jusqu’à l’installation."]],methodTag:"NOTRE SAVOIR-FAIRE",methodTitle:"Quatre métiers. Une seule équipe.",methods:[["Conception","Organisation des espaces, plans et visualisation 3D."],["Fabrication","Mobilier, vitrines, comptoirs et rangements sur mesure."],["Finition","Choix des matières, éclairage et détails décoratifs."],["Installation","Livraison, montage, réglages et remise de l’espace."]],teamTag:"L’ÉQUIPE EPSTAR",teamTitle:"Des profils complémentaires autour de votre projet.",teamText:"Concepteurs, techniciens, fabricants et installateurs collaborent dans un processus commun. Les informations et portraits réels de l’équipe seront ajoutés dans la version finale.",cta:"Construisons votre prochain espace.",ctaText:"Parlez-nous de votre activité, de vos dimensions et de votre vision.",note:"Les chiffres et informations détaillés seront validés avec les données officielles d’EPSTAR avant la mise en ligne publique."},
 ar:{tag:"من نحن",title:"نحوّل المساحات إلى أدوات للنجاح.",lead:"EPSTAR شركة جزائرية متخصصة في تصميم وتصنيع وتركيب تجهيزات حسب الطلب للمحترفين والأفراد.",intro:"من الصيدليات إلى المكاتب والمحلات وغرف النوم، نجمع الدراسة والتصميم والتصنيع والتركيب تحت سقف واحد لنقدّم مساحات متناسقة وعملية ومتينة.",discover:"اكتشف مشاريعنا",stats:[["4","مجالات متخصصة"],["100%","تصنيع حسب الطلب"],["1","فريق يرافقك من الدراسة إلى التركيب"]],story:"كل مشروع ناجح يبدأ بفهم جيد.",storyText:"لا ننطلق من كتالوج جاهز؛ نعاين المكان ونفهم طريقة استخدامه ثم نطوّر حلًا يناسب المقاسات والميزانية والهوية المطلوبة.",valuesTag:"التزاماتنا",valuesTitle:"نفس معيار الجودة في كل مرحلة.",values:[["01","الاستماع","فهم الاحتياجات الحقيقية قبل رسم الحل."],["02","الدقة","التحكم في القياسات والخامات وتفاصيل التشطيب."],["03","التناسق","ربط الجمال بالوظيفة وهوية المشروع."],["04","المتابعة","مرافقة العميل من الدراسة الأولى حتى التركيب."]],methodTag:"خبراتنا",methodTitle:"أربع خبرات، وفريق واحد.",methods:[["التصميم","تنظيم المساحة والمخططات والتصور ثلاثي الأبعاد."],["التصنيع","الأثاث والواجهات والكاونترات والخزائن حسب الطلب."],["التشطيب","اختيار الخامات والإضاءة والتفاصيل الديكورية."],["التركيب","التوصيل والتركيب والضبط وتسليم المساحة."]],teamTag:"فريق EPSTAR",teamTitle:"خبرات متكاملة حول مشروعك.",teamText:"يعمل المصممون والتقنيون والمصنّعون وفريق التركيب ضمن مسار واحد. ستتم إضافة معلومات وصور فريق EPSTAR الحقيقية في النسخة النهائية.",cta:"لنصنع مساحتك القادمة.",ctaText:"حدثنا عن نشاطك ومقاساتك ورؤيتك للمشروع.",note:"سيتم اعتماد الأرقام والمعلومات التفصيلية من بيانات EPSTAR الرسمية قبل الإطلاق العام."},
 en:{tag:"ABOUT EPSTAR",title:"We turn spaces into tools for success.",lead:"EPSTAR is an Algerian company specializing in the design, manufacture and installation of custom fit-outs for professionals and individuals.",intro:"From pharmacies and offices to retail and bedrooms, we bring study, design, manufacturing and fitting together under one roof to create coherent, functional and durable spaces.",discover:"Explore our projects",stats:[["4","Specialist sectors"],["100%","Custom manufacturing"],["1","Team from study to installation"]],story:"A successful project starts with real understanding.",storyText:"We do not begin with a fixed catalogue. We observe the site, understand how it will be used, then develop a response suited to the dimensions, budget and desired identity.",valuesTag:"OUR COMMITMENTS",valuesTitle:"One standard at every stage.",values:[["01","Listening","Understanding real needs before drawing the solution."],["02","Precision","Controlling measurements, materials and finishing details."],["03","Consistency","Connecting aesthetics, function and project identity."],["04","Follow-up","Staying present from the first study to installation."]],methodTag:"OUR EXPERTISE",methodTitle:"Four disciplines. One team.",methods:[["Design","Space planning, drawings and 3D visualization."],["Manufacturing","Custom furniture, showcases, counters and storage."],["Finishing","Materials, lighting and decorative details."],["Installation","Delivery, assembly, adjustments and handover."]],teamTag:"THE EPSTAR TEAM",teamTitle:"Complementary expertise around your project.",teamText:"Designers, technicians, manufacturers and installers collaborate in one process. Real team information and portraits will be added to the final version.",cta:"Let’s build your next space.",ctaText:"Tell us about your activity, dimensions and vision.",note:"Detailed figures and information will be validated against official EPSTAR data before the public launch."}
};

export default function AboutPage(){
 const {lang,setLang,theme,setTheme,rtl}=useProjectUi(),t=copy[lang];
 return <main className={`about-page ${rtl?"rtl ":""}${theme==="dark"?"dark":""}`} dir={rtl?"rtl":"ltr"}>
  <ProjectHeader {...{lang,setLang,theme,setTheme}}/>
  <section className="about-hero-page"><div className="about-hero-copy"><small>{t.tag}</small><h1>{t.title}</h1><p>{t.lead}</p><a className="primary-btn" href="/projects">{t.discover}</a></div><div className="about-hero-art"><span className="about-orbit"/><img className="art-main" src="/images/pharmacy-3d.png" alt="EPSTAR"/><img className="art-mini art-office" src="/images/office-3d.png" alt=""/><img className="art-mini art-shop" src="/images/shop-3d.png" alt=""/></div></section>
  <section className="about-manifesto"><div><small>EPSTAR / 01</small><h2>{t.story}</h2></div><div><p>{t.intro}</p><p>{t.storyText}</p></div></section>
  <section className="about-stats">{t.stats.map(x=><article key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></article>)}</section>
  <section className="about-values"><div className="about-section-title"><small>{t.valuesTag}</small><h2>{t.valuesTitle}</h2></div><div className="value-grid">{t.values.map(v=><article key={v[0]}><b>{v[0]}</b><span>✦</span><h3>{v[1]}</h3><p>{v[2]}</p></article>)}</div></section>
  <section className="about-craft"><div className="craft-photo"><img src="/images/office.png" alt="EPSTAR workspace"/><span>{t.methodTag}</span></div><div className="craft-copy"><small>{t.methodTag}</small><h2>{t.methodTitle}</h2>{t.methods.map((m,i)=><article key={m[0]}><b>0{i+1}</b><div><h3>{m[0]}</h3><p>{m[1]}</p></div></article>)}</div></section>
  <section className="about-team"><div className="team-model"><img src="/images/bedroom-3d.png" alt="EPSTAR custom interior"/></div><div><small>{t.teamTag}</small><h2>{t.teamTitle}</h2><p>{t.teamText}</p><span className="about-note">{t.note}</span></div></section>
  <section className="detail-quote"><div><small>EPSTAR ALGÉRIE</small><h2>{t.cta}</h2><p>{t.ctaText}</p></div><QuoteForm lang={lang}/></section>
  <ProjectFooter lang={lang}/>
 </main>
}
