export const projectOrder=["pharmacy-algiers","executive-office","premium-boutique","modern-bedroom","compact-pharmacy","open-workspace"] as const;
export type ProjectSlug=typeof projectOrder[number];
export type ProjectLang="fr"|"ar"|"en";

export const projectMedia:{[K in ProjectSlug]:{sector:string,image:string,model:string,position?:string}}={
  "pharmacy-algiers":{sector:"pharmacies",image:"/images/pharmacy.png",model:"/images/pharmacy-3d.png"},
  "executive-office":{sector:"bureaux",image:"/images/office.png",model:"/images/office-3d.png"},
  "premium-boutique":{sector:"commerces",image:"/images/shop.png",model:"/images/shop-3d.png"},
  "modern-bedroom":{sector:"chambres",image:"/images/bedroom.png",model:"/images/bedroom-3d.png"},
  "compact-pharmacy":{sector:"pharmacies",image:"/images/pharmacy.png",model:"/images/pharmacy-3d.png",position:"65% center"},
  "open-workspace":{sector:"bureaux",image:"/images/office.png",model:"/images/office-3d.png",position:"25% center"}
};

export const projectCopy={
  fr:{pageTitle:"Des espaces qui parlent par leurs détails.",pageText:"Une sélection de concepts de démonstration illustrant notre approche de l’agencement sur mesure.",all:"Tous",filters:{pharmacies:"Pharmacies",bureaux:"Bureaux",commerces:"Commerces",chambres:"Chambres"},demo:"CONCEPT DE DÉMONSTRATION",view:"Voir le projet",back:"Tous les projets",challenge:"Le besoin",solution:"Notre réponse",scope:"Interventions",similar:"Vous avez un projet similaire ?",similarText:"Partagez-nous votre espace, vos dimensions et vos objectifs. Nous vous proposerons une première orientation.",quote:"Demander une étude",before:"Avant",after:"Projection EPSTAR",items:{
    "pharmacy-algiers":{title:"Pharmacie Signature",city:"Alger • Concept",summary:"Un parcours clair, des produits visibles et un comptoir central pensé pour la fluidité.",challenge:"Organiser un espace étroit tout en conservant une circulation confortable, une forte capacité d’exposition et un accueil professionnel.",solution:"Un mobilier blanc rythmé par des accents rouges, des vitrines transparentes et des rangements intégrés pour alléger visuellement l’ensemble.",scope:["Étude d’implantation","Comptoirs sur mesure","Rayonnages muraux","Vitrines en verre","Éclairage intégré","Installation complète"]},
    "executive-office":{title:"Bureau Direction",city:"Oran • Concept",summary:"Une atmosphère sobre où le verre, le bois clair et les lignes noires renforcent l’image professionnelle.",challenge:"Réunir accueil, confidentialité et rangement dans un espace représentatif sans le surcharger.",solution:"Une composition architecturale équilibrée avec cloison vitrée, rangement toute hauteur et mobilier aux proportions maîtrisées.",scope:["Banque d’accueil","Bureau exécutif","Cloison vitrée","Bibliothèque","Rangements","Pose et finitions"]},
    "premium-boutique":{title:"Boutique Écrin",city:"Sétif • Concept",summary:"Une mise en scène premium qui attire le regard et donne à chaque produit sa place.",challenge:"Créer un parcours commercial élégant avec plusieurs niveaux d’exposition et un point de vente central.",solution:"Des vitrines éclairées, une île en verre et un comptoir courbe composent un espace cohérent et identifiable.",scope:["Vitrines murales","Îlot central","Comptoir de vente","Éclairage LED","Habillage mural","Installation"]},
    "modern-bedroom":{title:"Suite Harmonie",city:"Blida • Concept",summary:"Une chambre chaleureuse avec dressing intégré et rangements parfaitement dissimulés.",challenge:"Maximiser le rangement tout en préservant une atmosphère calme, légère et confortable.",solution:"Un ensemble coordonné en bois clair et tons neutres, animé par un détail rouge discret et un éclairage chaud.",scope:["Lit et tête de lit","Dressing","Chevets","Coiffeuse","Éclairage","Finitions"]},
    "compact-pharmacy":{title:"Pharmacie Urbaine",city:"Constantine • Concept",summary:"Une solution compacte qui exploite chaque mètre carré sans compromettre la présentation.",challenge:"Augmenter la capacité de stockage et rendre les familles de produits immédiatement lisibles.",solution:"Des modules verticaux, un comptoir compact et une hiérarchie visuelle claire facilitent le travail et l’achat.",scope:["Zoning","Mobilier compact","Réserve technique","Signalétique","Vitrines","Installation"]},
    "open-workspace":{title:"Workspace Ligne",city:"Alger • Concept",summary:"Un environnement de travail flexible, ordonné et lumineux pour une équipe en mouvement.",challenge:"Structurer plusieurs usages sans fermer la lumière ni rendre l’espace rigide.",solution:"Des postes modulaires, des séparations vitrées et des rangements communs organisent naturellement les flux.",scope:["Postes de travail","Salle de réunion","Rangements","Cloisons","Accueil","Installation"]}}
  },
  ar:{pageTitle:"مساحات تتحدث من خلال تفاصيلها.",pageText:"مجموعة مفاهيم تجريبية توضح أسلوبنا في تصميم وتجهيز المساحات حسب الطلب.",all:"الكل",filters:{pharmacies:"الصيدليات",bureaux:"المكاتب",commerces:"المحلات",chambres:"غرف النوم"},demo:"تصور تجريبي",view:"عرض المشروع",back:"كل المشاريع",challenge:"احتياج المشروع",solution:"حلّنا المقترح",scope:"الأعمال المنفذة",similar:"هل لديك مشروع مشابه؟",similarText:"شاركنا المساحة والمقاسات والأهداف، وسنقترح عليك تصورًا أوليًا مناسبًا.",quote:"اطلب دراسة مشروع",before:"قبل",after:"تصور EPSTAR",items:{
    "pharmacy-algiers":{title:"صيدلية Signature",city:"الجزائر • تصور",summary:"حركة واضحة وعرض أفضل للمنتجات وكاونتر مركزي يسهّل الخدمة.",challenge:"تنظيم مساحة ضيقة مع الحفاظ على سهولة الحركة وقدرة عرض كبيرة واستقبال احترافي.",solution:"أثاث أبيض بلمسات حمراء وخزائن زجاجية وتخزين مدمج يمنح المكان خفة وتنظيمًا.",scope:["دراسة التوزيع","كاونترات حسب الطلب","رفوف جدارية","واجهات زجاجية","إضاءة مدمجة","تركيب كامل"]},
    "executive-office":{title:"مكتب الإدارة",city:"وهران • تصور",summary:"بيئة هادئة تجمع الزجاج والخشب الفاتح والخطوط السوداء بصورة احترافية.",challenge:"الجمع بين الاستقبال والخصوصية والتخزين دون ازدحام المساحة.",solution:"تكوين معماري متوازن بفاصل زجاجي وخزائن مرتفعة وأثاث بأبعاد مدروسة.",scope:["كاونتر استقبال","مكتب تنفيذي","فاصل زجاجي","مكتبة","خزائن","تركيب وتشطيب"]},
    "premium-boutique":{title:"محل Écrin",city:"سطيف • تصور",summary:"عرض فاخر يجذب النظر ويمنح كل منتج مكانًا واضحًا.",challenge:"إنشاء مسار بيع أنيق مع مستويات عرض متعددة ونقطة دفع مركزية.",solution:"واجهات مضاءة وجزيرة زجاجية وكاونتر منحني تصنع هوية متناسقة للمحل.",scope:["واجهات جدارية","جزيرة وسطية","كاونتر بيع","إضاءة LED","كسوة جدارية","تركيب"]},
    "modern-bedroom":{title:"غرفة Harmonie",city:"البليدة • تصور",summary:"غرفة دافئة بدولاب مدمج وحلول تخزين مخفية بعناية.",challenge:"زيادة التخزين مع الحفاظ على جو هادئ وخفيف ومريح.",solution:"مجموعة متناسقة من الخشب الفاتح والألوان الهادئة مع لمسة حمراء وإضاءة دافئة.",scope:["سرير وخلفية","Dressing","طاولات جانبية","تسريحة","إضاءة","تشطيبات"]},
    "compact-pharmacy":{title:"صيدلية حضرية",city:"قسنطينة • تصور",summary:"حل مدمج يستغل كل متر دون التأثير على جودة العرض.",challenge:"رفع قدرة التخزين وتوضيح تصنيفات المنتجات بسرعة.",solution:"وحدات رأسية وكاونتر صغير وتسلسل بصري واضح يسهل العمل والشراء.",scope:["تقسيم المساحة","أثاث مدمج","مخزن تقني","إرشادات","خزائن عرض","تركيب"]},
    "open-workspace":{title:"مساحة عمل Ligne",city:"الجزائر • تصور",summary:"بيئة عمل مرنة ومنظمة ومضيئة لفريق دائم الحركة.",challenge:"تنظيم استخدامات مختلفة دون حجب الضوء أو جعل المكان جامدًا.",solution:"مكاتب مرنة وفواصل زجاجية وتخزين مشترك تنظم الحركة بصورة طبيعية.",scope:["محطات عمل","قاعة اجتماعات","خزائن","فواصل","استقبال","تركيب"]}}
  },
  en:{pageTitle:"Spaces that speak through their details.",pageText:"A selection of demonstration concepts illustrating our approach to custom fit-out.",all:"All",filters:{pharmacies:"Pharmacies",bureaux:"Offices",commerces:"Retail",chambres:"Bedrooms"},demo:"DEMONSTRATION CONCEPT",view:"View project",back:"All projects",challenge:"The brief",solution:"Our response",scope:"Scope of work",similar:"Planning a similar project?",similarText:"Share your space, dimensions and objectives. We will suggest an initial direction.",quote:"Request a study",before:"Before",after:"EPSTAR concept",items:{
    "pharmacy-algiers":{title:"Signature Pharmacy",city:"Algiers • Concept",summary:"Clear circulation, strong product visibility and a central counter designed for smooth service.",challenge:"Organize a narrow space while preserving comfortable movement, display capacity and a professional welcome.",solution:"White furniture with red accents, transparent showcases and integrated storage keep the whole space visually light.",scope:["Layout study","Custom counters","Wall shelving","Glass showcases","Integrated lighting","Complete installation"]},
    "executive-office":{title:"Executive Office",city:"Oran • Concept",summary:"A restrained atmosphere where glass, pale wood and black lines reinforce a professional image.",challenge:"Combine reception, privacy and storage in a representative space without visual clutter.",solution:"A balanced composition with glazed partitions, full-height storage and precisely proportioned furniture.",scope:["Reception desk","Executive desk","Glass partition","Library","Storage","Fitting and finishes"]},
    "premium-boutique":{title:"Écrin Boutique",city:"Sétif • Concept",summary:"A premium presentation that draws attention and gives every product its place.",challenge:"Create an elegant sales journey with multiple display levels and a central checkout.",solution:"Lit showcases, a glass island and a curved counter create a coherent, memorable retail identity.",scope:["Wall showcases","Central island","Sales counter","LED lighting","Wall cladding","Installation"]},
    "modern-bedroom":{title:"Harmonie Suite",city:"Blida • Concept",summary:"A warm bedroom with an integrated wardrobe and discreet, intelligent storage.",challenge:"Maximize storage while preserving a calm, light and comfortable atmosphere.",solution:"A coordinated set in pale wood and neutral tones, animated by a restrained red detail and warm lighting.",scope:["Bed and headboard","Wardrobe","Nightstands","Vanity","Lighting","Finishes"]},
    "compact-pharmacy":{title:"Urban Pharmacy",city:"Constantine • Concept",summary:"A compact solution that uses every square metre without compromising presentation.",challenge:"Increase storage capacity and make product families instantly readable.",solution:"Vertical modules, a compact counter and clear visual hierarchy simplify both work and shopping.",scope:["Zoning","Compact furniture","Technical storage","Signage","Showcases","Installation"]},
    "open-workspace":{title:"Ligne Workspace",city:"Algiers • Concept",summary:"A flexible, orderly and bright work environment for a team in motion.",challenge:"Structure multiple uses without blocking light or making the space rigid.",solution:"Modular desks, glazed partitions and shared storage naturally organize circulation.",scope:["Workstations","Meeting room","Storage","Partitions","Reception","Installation"]}}
  }
} as const;
