"use client";

import {useEffect,useState} from "react";
import {useQuoteCart} from "../../components/use-quote-cart";
import {groups,type Lang,type Product} from "../data";

const words={fr:{back:"Catalogue",tag:"RÉFÉRENCE EPSTAR",materials:"Matières proposées",options:"Options de personnalisation",add:"Ajouter au devis",added:"Ajouté au devis",request:"Voir ma demande",note:"Cette fiche est une référence de démonstration. La solution finale est adaptée au relevé, à l’usage et au budget du projet.",study:"Demander une étude",process:"Chaque pièce commence par l’usage de l’espace, puis est ajustée dans ses dimensions, matériaux et détails de finition.",steps:["Fiche produit","Ajout à la demande","Envoi de la demande"]},ar:{back:"الكتالوج",tag:"نموذج EPSTAR",materials:"الخامات المقترحة",options:"خيارات التخصيص",add:"أضف إلى طلب السعر",added:"تمت الإضافة",request:"عرض طلبي",note:"هذه البطاقة نموذج تجريبي. نخصص الحل النهائي وفق القياسات والاستخدام وميزانية المشروع.",study:"اطلب دراسة",process:"كل قطعة تبدأ من طريقة استخدام المساحة، ثم نعدل المقاسات والخامات وتفاصيل التشطيب.",steps:["تفاصيل المنتج","الإضافة إلى طلبي","إرسال الطلب"]},en:{back:"Catalogue",tag:"EPSTAR REFERENCE",materials:"Suggested materials",options:"Customisation options",add:"Add to quote",added:"Added to quote",request:"View my request",note:"This sheet is a demonstration reference. The final solution is tailored to the site survey, use and project budget.",study:"Request a study",process:"Every piece starts with how the space is used, then dimensions, materials and finishing details are adjusted.",steps:["Product details","Add to request","Send request"]}};

export default function ProductDetail({product}:{product:Product}){const [lang,setLang]=useState<Lang>("fr"),[theme,setTheme]=useState<"light"|"dark">("light");const {cart,setCart}=useQuoteCart();const added=cart.includes(product.id);useEffect(()=>{const saved=localStorage.getItem("epstar-language");if(saved==="ar"||saved==="fr"||saved==="en")setLang(saved)},[]);
  useEffect(()=>{const s=localStorage.getItem("epstar-theme") as "light"|"dark"|null;setTheme(s||"light");},[product.id]);useEffect(()=>{document.documentElement.lang=lang;localStorage.setItem("epstar-language",lang);document.documentElement.dir=lang==="ar"?"rtl":"ltr";document.documentElement.dataset.theme=theme},[lang,theme]);const t=words[lang],rtl=lang==="ar";function add(){setCart(c=>c.includes(product.id)?c.filter(x=>x!==product.id):[...c,product.id])}return <main className={`detail-page ${theme==="dark"?"dark":""} ${rtl?"rtl":""}`} dir={rtl?"rtl":"ltr"}><header className="catalogue-nav"><a href="/"><img src="/epstar-logo.png" alt="EPSTAR"/></a><div><a href="/catalogue">← {t.back}</a><a className="catalogue-count" href="/quote">{t.request} ({cart.length})</a><button onClick={()=>setTheme(x=>x==="dark"?"light":"dark")}>{theme==="dark"?"☀":"☾"}</button><div className="catalogue-lang">{(["ar","fr","en"] as Lang[]).map(x=><button className={x===lang?"active":""} key={x} onClick={()=>setLang(x)}>{x}</button>)}</div></div></header><ol className="journey-flow detail-flow" aria-label={lang==="ar"?"خطوات الطلب":"Request steps"}>{t.steps.map((step,i)=><li key={step} className={i===0?"active":""}>{step}</li>)}</ol><section className="detail-hero"><div className="detail-copy"><small>{t.tag} · {product.id.toUpperCase()}</small><p className="detail-group">{groups[product.group][lang]}</p><h1>{product.name[lang]}</h1><p>{product.intro[lang]}</p><button className={added?"added":""} onClick={add}>{added?t.added:t.add}<span>{added?"✓":"+"}</span></button>{added&&<a className="detail-next" href="/quote">{t.request} <span>↗</span></a>}</div><div className="detail-visual"><img src={product.image} alt={product.name[lang]}/></div></section><section className="detail-specs"><article><small>01</small><h2>{t.materials}</h2><ul>{product.materials[lang].map(x=><li key={x}>{x}</li>)}</ul></article><article><small>02</small><h2>{t.options}</h2><ul>{product.options[lang].map(x=><li key={x}>{x}</li>)}</ul></article><article className="detail-note"><small>03</small><p>{t.note}</p><a href="/quote">{t.study} <span>↗</span></a></article></section><section className="detail-process"><span>EPSTAR</span><p>{t.process}</p></section></main>}
