export type Lang = "fr" | "ar" | "en";
export type Product = {
  id:string; slug:string; group:"pharmacy"|"office"|"retail"|"interiors"; image:string;
  category:Record<Lang,string>; name:Record<Lang,string>; detail:Record<Lang,string>;
  intro:Record<Lang,string>; materials:Record<Lang,string[]>; options:Record<Lang,string[]>;
};

const p=(id:string,slug:string,group:Product["group"],image:string,category:Product["category"],name:Product["name"],detail:Product["detail"],intro:Product["intro"],materials:Product["materials"],options:Product["options"]):Product=>({id,slug,group,image,category,name,detail,intro,materials,options});

export const catalog:Product[]=[
  p("ph-c01","comptoir-ligne-c01","pharmacy","/images/pharmacy-premium.png",{fr:"Pharmacie",ar:"صيدليات",en:"Pharmacy"},{fr:"Comptoir Ligne C01",ar:"كاونتر لاين C01",en:"Line Counter C01"},{fr:"Fabrication sur mesure",ar:"تصنيع حسب الطلب",en:"Made to measure"},{fr:"Un comptoir d’accueil modulable qui structure l’espace de vente et facilite l’échange avec chaque client.",ar:"كاونتر استقبال مرن ينظم مساحة البيع ويسهل التواصل مع كل عميل.",en:"A modular reception counter that structures the sales area and makes every client interaction easier."},{fr:["Panneaux stratifiés","Métal thermolaqué","Verre sécurisé"],ar:["ألواح مغلفة","معدن مطلي حرارياً","زجاج آمن"],en:["Laminated panels","Powder-coated metal","Safety glass"]},{fr:["Dimensions sur plan","Accès PMR","Éclairage intégré"],ar:["مقاسات حسب المخطط","وصول مريح","إضاءة مدمجة"],en:["Custom dimensions","Accessible layout","Integrated lighting"]}),
  p("ph-r05","rayonnage-pharmacie-r05","pharmacy","/images/pharmacy-3d.png",{fr:"Pharmacie",ar:"صيدليات",en:"Pharmacy"},{fr:"Rayonnage Pharmacie R05",ar:"رفوف صيدلية R05",en:"Pharmacy Shelving R05"},{fr:"Visibilité, réserve et circulation",ar:"وضوح وتخزين وحركة",en:"Visibility, storage and flow"},{fr:"Un système mural conçu pour mettre les gammes en valeur tout en gardant une réserve accessible.",ar:"نظام جداري يبرز المنتجات ويحافظ على التخزين في متناول اليد.",en:"A wall system that highlights products while keeping back stock within reach."},{fr:["Mélaminé haute résistance","Aluminium","LED"],ar:["ميلامين عالي المقاومة","ألمنيوم","إضاءة LED"],en:["High-resistance melamine","Aluminium","LED"]},{fr:["Modules ouverts ou fermés","Signalétique de gamme","Tiroirs de réserve"],ar:["وحدات مفتوحة أو مغلقة","لافتات الأقسام","أدراج تخزين"],en:["Open or closed modules","Range signage","Storage drawers"]}),
  p("of-d02","bureau-direction-d02","office","/images/office-premium.png",{fr:"Bureaux",ar:"مكاتب",en:"Workspace"},{fr:"Bureau Direction D02",ar:"مكتب إداري D02",en:"Executive Desk D02"},{fr:"Bois, métal et rangement intégré",ar:"خشب ومعدن وتخزين مدمج",en:"Wood, metal and integrated storage"},{fr:"Un poste de direction qui donne une présence claire à l’espace tout en intégrant le rangement essentiel.",ar:"مكتب إداري يمنح المكان حضوراً واضحاً مع تخزين أساسي مدمج.",en:"An executive workstation that gives the room presence while integrating essential storage."},{fr:["Bois plaqué ou stratifié","Piètement métal","Quincaillerie professionnelle"],ar:["خشب بقشرة أو مغلف","قاعدة معدنية","إكسسوارات احترافية"],en:["Veneer or laminate","Metal base","Professional hardware"]},{fr:["Retour latéral","Passe-câbles","Caisson mobile"],ar:["وحدة جانبية","ممرات للكابلات","خزانة متحركة"],en:["Side return","Cable ports","Mobile pedestal"]}),
  p("of-r07","reception-atelier-r07","office","/images/office-3d.png",{fr:"Bureaux",ar:"مكاتب",en:"Workspace"},{fr:"Réception Atelier R07",ar:"استقبال أتيلييه R07",en:"Atelier Reception R07"},{fr:"Première impression maîtrisée",ar:"انطباع أول احترافي",en:"A controlled first impression"},{fr:"Un accueil pensé comme un point de repère pour les visiteurs et une station de travail efficace pour l’équipe.",ar:"استقبال مصمم كنقطة توجيه للزوار ومحطة عمل عملية للفريق.",en:"A reception designed as a clear visitor landmark and an efficient team workstation."},{fr:["MDF laqué","Bois décoratif","LED indirecte"],ar:["MDF مطلي","خشب ديكوري","إضاءة غير مباشرة"],en:["Lacquered MDF","Decorative wood","Indirect LED"]},{fr:["Logo intégré","Façade rétroéclairée","Zone d’attente"],ar:["شعار مدمج","واجهة مضيئة","منطقة انتظار"],en:["Integrated logo","Backlit façade","Waiting area"]}),
  p("rt-v03","presentoir-vision-v03","retail","/images/shop-premium.png",{fr:"Commerce",ar:"محلات",en:"Retail"},{fr:"Présentoir Vision V03",ar:"وحدة عرض فيجن V03",en:"Vision Display V03"},{fr:"Éclairage et finitions au choix",ar:"إضاءة وتشطيبات حسب الاختيار",en:"Custom lighting and finishes"},{fr:"Une unité de présentation qui guide le regard, organise les références et renforce l’identité du point de vente.",ar:"وحدة عرض توجه النظر وتنظم المنتجات وتعزز هوية نقطة البيع.",en:"A presentation unit that guides the eye, organises references and strengthens the retail identity."},{fr:["Verre trempé","Aluminium","Panneaux décoratifs"],ar:["زجاج مقوى","ألمنيوم","ألواح ديكورية"],en:["Tempered glass","Aluminium","Decorative panels"]},{fr:["Fond éclairé","Étagères réglables","Branding intégré"],ar:["خلفية مضيئة","رفوف قابلة للتعديل","هوية مدمجة"],en:["Backlit background","Adjustable shelves","Integrated branding"]}),
  p("rt-c08","caisse-atelier-c08","retail","/images/shop-3d.png",{fr:"Commerce",ar:"محلات",en:"Retail"},{fr:"Caisse Atelier C08",ar:"كاونتر كاشير C08",en:"Atelier Cash Desk C08"},{fr:"Flux de vente organisé",ar:"حركة بيع منظمة",en:"Organised sales flow"},{fr:"Un comptoir de caisse adapté à la file, aux équipements de paiement et au rangement de proximité.",ar:"كاونتر كاشير مناسب للطابور وأجهزة الدفع والتخزين القريب.",en:"A cash desk tailored for queues, payment equipment and close-at-hand storage."},{fr:["Stratifié compact","Acier","Quartz ou solid surface"],ar:["لامينيت مدمج","فولاذ","كوارتز أو سطح صلب"],en:["Compact laminate","Steel","Quartz or solid surface"]},{fr:["Passage câbles","Zone emballage","Rangement sécurisé"],ar:["ممر كابلات","منطقة تغليف","تخزين آمن"],en:["Cable management","Packing zone","Secure storage"]}),
  p("in-w04","dressing-module-w04","interiors","/images/bedroom-3d.png",{fr:"Intérieurs",ar:"الأثاث الداخلي",en:"Interiors"},{fr:"Dressing Module W04",ar:"دولاب موديل W04",en:"Module Wardrobe W04"},{fr:"Composition personnalisable",ar:"تكوين قابل للتخصيص",en:"Customisable composition"},{fr:"Un dressing organisé selon vos habitudes, vos dimensions et le style souhaité pour la chambre.",ar:"دولاب منظم حسب عاداتك ومقاساتك والأسلوب المطلوب للغرفة.",en:"A wardrobe organised around your habits, dimensions and the desired bedroom style."},{fr:["Mélaminé premium","Miroir","Aluminium"],ar:["ميلامين فاخر","مرآة","ألمنيوم"],en:["Premium melamine","Mirror","Aluminium"]},{fr:["Portes coulissantes","Éclairage intérieur","Aménagement sur mesure"],ar:["أبواب منزلقة","إضاءة داخلية","تقسيم حسب الطلب"],en:["Sliding doors","Interior lighting","Custom layout"]}),
  p("in-b09","lit-atelier-b09","interiors","/images/bedroom.png",{fr:"Intérieurs",ar:"الأثاث الداخلي",en:"Interiors"},{fr:"Lit Atelier B09",ar:"سرير أتيلييه B09",en:"Atelier Bed B09"},{fr:"Une pièce centrale équilibrée",ar:"قطعة مركزية متوازنة",en:"A balanced central piece"},{fr:"Un lit sur mesure avec tête de lit, rangements et finitions coordonnées avec le reste de la pièce.",ar:"سرير حسب الطلب مع رأس سرير وتخزين وتشطيبات متناسقة مع بقية الغرفة.",en:"A custom bed with headboard, storage and finishes coordinated with the rest of the room."},{fr:["Bois décoratif","Tissu ou cuir","MDF laqué"],ar:["خشب ديكوري","قماش أو جلد","MDF مطلي"],en:["Decorative wood","Fabric or leather","Lacquered MDF"]},{fr:["Tête de lit intégrée","Tables de chevet","Tiroirs bas"],ar:["رأس سرير مدمج","طاولات جانبية","أدراج سفلية"],en:["Integrated headboard","Nightstands","Low drawers"]})
];

export const groups:Record<Product["group"],Record<Lang,string>>={
  pharmacy:{fr:"Pharmacies",ar:"الصيدليات",en:"Pharmacies"}, office:{fr:"Bureaux",ar:"المكاتب",en:"Offices"}, retail:{fr:"Commerces",ar:"المحلات",en:"Retail"}, interiors:{fr:"Intérieurs",ar:"الأثاث الداخلي",en:"Interiors"}
};
